# library(pipelineR)
message("Starting Pipeline...")
batch_size_jenkins <- as.integer(Sys.getenv("JENKINS_BATCH_SIZE"))
message("Batch size: ", batch_size_jenkins)
pipelineR::start_pipeline(.batch_size = batch_size_jenkins)
message("start_pipeline() run without crash.")
